
[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"
#

[window.padding]
x = 12
y = 12

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[window]
opacity = 1.0
