require("plugins_config.formatter")
require("plugins_config.nvimTree")
require("plugins_config.nvim-treesitter")
require("plugins_config.telescope")
require("plugins_config.lsp")
require("plugins_config.nvim-cmp")
require("plugins_config.mason")
